// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqjxgsDYw-ORmgrkCu4ImW69iMKp2IJwA',
    appId: '1:465802225394:web:df3c5e2c792c79bd1e926b',
    messagingSenderId: '465802225394',
    projectId: 'truco-royale',
    authDomain: 'truco-royale.firebaseapp.com',
    storageBucket: 'truco-royale.appspot.com',
    measurementId: 'G-YSN1BK8KEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNNMqatKZP-YhzJMRkAW2RMCmVpbWBvA',
    appId: '1:465802225394:android:bdaf4ad349cad78d1e926b',
    messagingSenderId: '465802225394',
    projectId: 'truco-royale',
    storageBucket: 'truco-royale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpiUn_docUYiRbz50kfTph2skUsc7C8M',
    appId: '1:465802225394:ios:5187cd2709b81a601e926b',
    messagingSenderId: '465802225394',
    projectId: 'truco-royale',
    storageBucket: 'truco-royale.appspot.com',
    iosBundleId: 'com.example.trucoView20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIpiUn_docUYiRbz50kfTph2skUsc7C8M',
    appId: '1:465802225394:ios:5187cd2709b81a601e926b',
    messagingSenderId: '465802225394',
    projectId: 'truco-royale',
    storageBucket: 'truco-royale.appspot.com',
    iosBundleId: 'com.example.trucoView20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqjxgsDYw-ORmgrkCu4ImW69iMKp2IJwA',
    appId: '1:465802225394:web:a0f8b6bf01a928c41e926b',
    messagingSenderId: '465802225394',
    projectId: 'truco-royale',
    authDomain: 'truco-royale.firebaseapp.com',
    storageBucket: 'truco-royale.appspot.com',
    measurementId: 'G-H4F2QPPL74',
  );
}
